# Generated by Django 4.2.23 on 2025-10-09 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_type', models.PositiveSmallIntegerField(choices=[(1, 'FILL_MASK'), (2, 'GUESS_REPLACEMENT')])),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(default='brak opisu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sentence', models.TextField()),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.text')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_feedback', models.SmallIntegerField()),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('options', models.JSONField()),
                ('quiz_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizdata')),
                ('sentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.JSONField()),
                ('user_comment', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('quiz_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizanswer')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.questiondata'),
        ),
    ]
