# Generated by Django 5.2.3 on 2025-07-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('word', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
