# Generated by Django 5.2.3 on 2025-07-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_wordrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordrating',
            old_name='rating',
            new_name='value',
        ),
    ]
