# Generated by Django 4.2.23 on 2025-10-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_text_quizdata_quiz_alter_sentence_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='user_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='quiz_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='quiz.quizdata'),
        ),
    ]
