# Generated by Django 4.2.23 on 2025-10-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_questionanswer_user_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='user_feedback',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
