# Generated by Django 5.2.3 on 2025-07-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_rating_wordrating_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordrating',
            old_name='word',
            new_name='rated_word',
        ),
    ]
