# Generated by Django 4.2.23 on 2025-10-13 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quizanswer_user_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qestions', to='quiz.questiondata'),
        ),
    ]
