# Generated by Django 4.2.23 on 2025-07-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_word_wordrating_rated_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('chosen_word', models.TextField()),
                ('missing_word', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
    ]
