# Generated by Django 4.2.23 on 2025-07-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_chooseword_remove_book_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_word', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ChooseWord',
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
