# Generated by Django 4.2.23 on 2025-07-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_wordinsert_delete_chooseword_book_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_word', models.TextField()),
                ('sentence', models.TextField()),
                ('hidden_word', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='WordInsert',
        ),
    ]
