# Generated by Django 4.2.23 on 2025-10-13 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_question_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quiz.questiondata'),
        ),
    ]
