# Generated by Django 4.2.23 on 2025-07-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_insertword_delete_wordinsert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('chosen_word', models.TextField()),
            ],
        ),
    ]
