# Generated by Django 4.2.23 on 2025-10-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_question_question_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondata',
            name='sentence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='quiz.sentence'),
        ),
    ]
