# Generated by Django 4.2.23 on 2025-07-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_chooseword'),
    ]

    operations = [
        migrations.AddField(
            model_name='chooseword',
            name='option_1',
            field=models.CharField(default='brak_opcji', max_length=100),
        ),
        migrations.AddField(
            model_name='chooseword',
            name='option_2',
            field=models.CharField(default='brak_opcji', max_length=100),
        ),
        migrations.AddField(
            model_name='chooseword',
            name='option_3',
            field=models.CharField(default='brak_opcji', max_length=100),
        ),
        migrations.AddField(
            model_name='chooseword',
            name='option_4',
            field=models.CharField(default='brak_opcji', max_length=100),
        ),
        migrations.AlterField(
            model_name='chooseword',
            name='chosen_word',
            field=models.CharField(max_length=100),
        ),
    ]
