# Generated by Django 4.2.23 on 2025-10-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_questiondata_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='has_data',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
