# Generated by Django 4.2.23 on 2025-08-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_chooseword_option_1_chooseword_option_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chooseword',
            old_name='chosen_word',
            new_name='replaced_word',
        ),
    ]
