# Generated by Django 4.2.23 on 2025-11-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_sentence_has_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='quiz.questiondata'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.JSONField(default=dict),
        ),
    ]
