# Generated by Django 4.2.23 on 2025-11-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_question_question_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='quiz_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizanswer'),
        ),
    ]
