# Generated by Django 4.2.23 on 2025-11-03 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_questionanswer_quiz_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quiz'),
        ),
    ]
