# Generated by Django 4.2.23 on 2025-09-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_text_sentece'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='text',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Sentece',
        ),
        migrations.AddField(
            model_name='sentence',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.text'),
        ),
    ]
