# Generated by Django 4.2.23 on 2025-11-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_quizanswer_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswer',
            name='username',
        ),
    ]
