# Generated by Django 4.2.23 on 2025-09-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_sentence_alter_text_source_delete_sentece_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillMaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.IntegerField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='FillMaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_index', models.IntegerField(default=-1)),
                ('option1_str', models.CharField(max_length=30)),
                ('option1_score', models.FloatField(default=-1.0)),
                ('option2_str', models.CharField(max_length=30)),
                ('option2_score', models.FloatField(default=-1.0)),
                ('option3_str', models.CharField(max_length=30)),
                ('option3_score', models.FloatField(default=-1.0)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.sentence')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='ChooseWord',
        ),
        migrations.DeleteModel(
            name='InsertWord',
        ),
        migrations.DeleteModel(
            name='WordRating',
        ),
    ]
