# Generated by Django 4.2.23 on 2025-11-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_remove_quizanswer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
