# Generated by Django 4.2.23 on 2025-09-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_fillmaskanswer_fillmaskdata_delete_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='source',
        ),
        migrations.AddField(
            model_name='fillmaskanswer',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fillmaskdata',
            name='mask_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.TextField(),
        ),
    ]
