# Generated by Django 4.2.23 on 2025-11-14 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_quizanswer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiondata',
            old_name='options',
            new_name='question_data',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.text'),
        ),
    ]
