# Generated by Django 4.2.23 on 2025-09-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_text_source_fillmaskanswer_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillmaskdata',
            name='mask_str',
            field=models.CharField(editable=False, max_length=30, null=True),
        ),
    ]
