# Generated by Django 4.2.23 on 2025-12-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_rename_options_questiondata_question_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FILL_MASK'), (2, 'GUESS_REPLACEMENT'), (3, 'WORD_SENSE_DISAMBIGUATION')]),
        ),
    ]
