# Generated by Django 4.2.23 on 2025-09-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_fillmaskdata_mask_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillmaskdata',
            name='mask_str',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
    ]
