# Generated by Django 4.2.23 on 2025-09-16 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_fillmaskdata_mask_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillmaskanswer',
            name='sentence',
        ),
        migrations.AddField(
            model_name='fillmaskanswer',
            name='fill_mask_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.fillmaskdata'),
        ),
        migrations.AlterField(
            model_name='fillmaskanswer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
