# Generated by Django 4.2.23 on 2025-09-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_remove_fillmaskanswer_sentence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='fillmaskanswer',
            name='fill_mask_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_mask_answers', to='quiz.fillmaskdata'),
        ),
    ]
