# Generated by Django 4.2.23 on 2025-09-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_alter_fillmaskanswer_fill_mask_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillmaskanswer',
            name='fill_mask_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_mask_answers', to='quiz.fillmaskdata'),
        ),
    ]
