# Generated by Django 4.2.23 on 2025-09-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_alter_fillmaskanswer_fill_mask_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillmaskdata',
            name='mask_str',
            field=models.CharField(max_length=30),
        ),
    ]
