# Generated by Django 4.2.23 on 2025-09-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_alter_fillmaskdata_mask_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
