# Generated by Django 4.2.23 on 2025-09-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_alter_text_id_alter_text_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
