# Generated by Django 4.2.23 on 2025-09-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_alter_sentence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillmaskdata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
