# Generated by Django 4.2.23 on 2025-09-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_alter_fillmaskdata_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.RemoveField(
            model_name='fillmaskanswer',
            name='fill_mask_data',
        ),
        migrations.AddField(
            model_name='fillmaskanswer',
            name='sentence',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quiz.sentence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fillmaskdata',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_mask_data_for_sentence', to='quiz.sentence'),
        ),
    ]
