# Generated by Django 4.2.23 on 2025-09-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_delete_quiz_remove_fillmaskanswer_fill_mask_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fillmaskanswer',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.sentence'),
        ),
        migrations.AlterField(
            model_name='fillmaskdata',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_data', to='quiz.sentence'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='quiz.quiz'),
        ),
    ]
