# Generated by Django 4.2.23 on 2025-09-24 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_quiz_alter_fillmaskanswer_sentence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='text_images/'),
        ),
        migrations.AlterField(
            model_name='fillmaskdata',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_data', to='quiz.sentence'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences_quiz', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences_text', to='quiz.text'),
        ),
    ]
