# Generated by Django 4.2.23 on 2025-09-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_text_image_alter_fillmaskdata_sentence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillmaskanswer',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='fillmaskdata',
            name='sentence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_data', to='quiz.sentence'),
        ),
    ]
