# Generated by Django 4.2.23 on 2025-10-01 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_fillmaskanswer_quiz_alter_fillmaskdata_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='text',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.text'),
        ),
    ]
