# Generated by Django 4.2.23 on 2025-10-01 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_quiz_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='question_type',
            field=models.CharField(choices=[('1', 'Fill Mask'), ('2', 'Guess Replacement')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='fillmaskanswer',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='text',
            unique_together={('title', 'question_type')},
        ),
        migrations.CreateModel(
            name='GuessReplacementData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_replacement', models.BooleanField()),
                ('replacement_index', models.IntegerField(blank=True, default=-1, null=True)),
                ('replacing_str', models.CharField(blank=True, max_length=25, null=True)),
                ('sentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='GuessReplacementAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ans', models.BooleanField()),
                ('ans_correct', models.BooleanField()),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
    ]
