# Generated by Django 4.2.23 on 2025-10-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_text_question_type_alter_fillmaskanswer_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='question_type',
            field=models.CharField(choices=[('1', 'Fill Mask'), ('2', 'Guess Replacement')], max_length=1),
        ),
    ]
