# Generated by Django 4.2.23 on 2025-10-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_alter_text_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='question_type',
            field=models.CharField(choices=[('Fill Mask', 'Fill Mask'), ('Guess Replacement', 'Guess Replacement')], max_length=100),
        ),
    ]
