# Generated by Django 4.2.23 on 2025-10-04 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_alter_text_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='text',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.text'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='quiz.text'),
        ),
    ]
