# Generated by Django 4.2.23 on 2025-10-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_alter_quiz_text_alter_sentence_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='text',
        ),
        migrations.AddField(
            model_name='quiz',
            name='texts',
            field=models.ManyToManyField(related_name='quizzes', to='quiz.text'),
        ),
        migrations.AlterField(
            model_name='fillmaskdata',
            name='sentence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fill_mask_data', to='quiz.sentence'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
