# Generated by Django 4.2.23 on 2025-10-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_remove_quiz_text_quiz_texts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='question_type',
            field=models.CharField(choices=[('FM', 'FM'), ('GR', 'GR')], max_length=100),
        ),
    ]
